"""
Holistic Simulation Suite: Scrub & Sunseal
Tests all components across multiple runs to verify stability and zero regressions.
"""

import os
import subprocess
import time
import shutil
from pathlib import Path

# --- SETTINGS ---
BASE_DIR = Path("/home/clara/SentryScrub_Pro")
SCRUB_PATH = BASE_DIR / "sscrub.py"
UNSEAL_PATH = BASE_DIR / "sunseal.py"
TEST_FILE = BASE_DIR / "sim_holistic_test.csv"
OUT_FILE = BASE_DIR / "sim_holistic_out.csv"
OUT_EPHEMERAL = BASE_DIR / "sim_holistic_ephemeral.csv"
REC_MASTER = BASE_DIR / "sim_rec_master.csv"
REC_EPH = BASE_DIR / "sim_rec_eph.csv"

VENV_PYTHON = BASE_DIR / ".sentry_venv" / "bin" / "python3"

ITERATIONS = 3

def clean_environment():
    """Deterministic state: wipe all artifacts."""
    files_to_remove = [
        TEST_FILE, OUT_FILE, OUT_EPHEMERAL, REC_MASTER, REC_EPH,
        BASE_DIR / "master.key", BASE_DIR / "hash.salt",
        BASE_DIR / "config.yaml", BASE_DIR / "discovery_rules.yaml",
        BASE_DIR / "scrub_audit.json"
    ]
    for f in files_to_remove:
        if f.exists(): f.unlink()
        
    # Remove versioned backups
    for f in BASE_DIR.glob("sim_holistic_out(*).csv"):
        f.unlink()

def create_dummy_data():
    with open(TEST_FILE, "w") as f:
        f.write("id,username,ssn,balance,notes\n")
        f.write("1,johndoe,123-45-678,5000,secret info\n")
        f.write("2,janedoe,987-65-432,250,classified data\n")

def run_cmd(args, stdin_data=None, wait=True):
    proc = subprocess.Popen(
        args,
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, cwd=BASE_DIR
    )
    if stdin_data and not wait:
        proc.stdin.write(stdin_data)
        proc.stdin.flush()
        return proc
        
    out, _ = proc.communicate(input=stdin_data)
    return proc.returncode, out

def run_iteration(iteration):
    print(f"\n" + "="*50)
    print(f"  STARTING ITERATION {iteration}/{ITERATIONS}")
    print("="*50)
    
    clean_environment()
    create_dummy_data()
    
    # 1. Generate Keys (simulating 'y' input just in case)
    print("  [1/9] Generating Master Keys...")
    rc, out = run_cmd([str(VENV_PYTHON), str(SCRUB_PATH), "--generate-keys"], "y\n")
    if not (BASE_DIR / "master.key").exists():
        return False, "Failed to generate master.key"
        
    # 2. Learn new rule
    print("  [2/9] Teaching Discovery Engine...")
    rc, out = run_cmd([str(VENV_PYTHON), str(SCRUB_PATH), "learn", "-k", "notes", "-s", "MASK"])
    
    # 3. Auto-Discover
    print("  [3/9] Running Auto-Discovery...")
    rc, out = run_cmd([str(VENV_PYTHON), str(SCRUB_PATH), "discover", "-i", str(TEST_FILE)])
    if not (BASE_DIR / "config.yaml").exists():
        return False, "Config.yaml not generated by discover"
        
    # 4. Manual Add & Ignore
    print("  [4/9] Testing Config Overrides (Add/Ignore)...")
    run_cmd([str(VENV_PYTHON), str(SCRUB_PATH), "add", "-c", "balance", "-s", "MASK"])
    run_cmd([str(VENV_PYTHON), str(SCRUB_PATH), "ignore", "-c", "username"])
    
    # 5. Standard Streaming Run (Master Key)
    print("  [5/9] Streaming Encryption (Master Key)...")
    rc, out = run_cmd([str(VENV_PYTHON), str(SCRUB_PATH), "run", "-i", str(TEST_FILE), "-o", str(OUT_FILE)])
    if not OUT_FILE.exists():
        return False, "Streaming run failed to produce output"
        
    # 6. Turbo Run (Master Key)
    print("  [6/9] Turbo Encryption (Master Key)...")
    rc, out = run_cmd([str(VENV_PYTHON), str(SCRUB_PATH), "run", "-i", str(TEST_FILE), "-o", str(OUT_FILE), "--turbo", "--force"])
    
    # 7. Recovery (Master Key)
    print("  [7/9] Sunseal Recovery (Master Key)...")
    rc, out = run_cmd([str(VENV_PYTHON), str(UNSEAL_PATH), "-i", str(OUT_FILE), "-o", str(REC_MASTER), "-c", "ssn"])
    with open(REC_MASTER, "r") as f:
        data = f.read()
        if "123-45-678" not in data:
            return False, f"Master recovery failed. Content: {data[:100]}"
            
    # 8. Ephemeral Run
    print("  [8/9] Ephemeral Encryption (One-Time Key)...")
    proc = subprocess.Popen(
        [str(VENV_PYTHON), str(SCRUB_PATH), "run", "-i", str(TEST_FILE), "-o", str(OUT_EPHEMERAL), "--ephemeral", "--force"],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, cwd=BASE_DIR
    )
    
    eph_key = None
    start = time.time()
    while True:
        line = proc.stdout.readline()
        if not line: break
        if "KEY:" in line:
            eph_key = line.split("KEY:")[1].strip()
            eph_key = "".join(c for c in eph_key if c.isalnum() or c in "-_")
            proc.stdin.write("\n")
            proc.stdin.flush()
        if time.time() - start > 10:
            proc.kill()
            return False, "Timeout waiting for ephemeral key"
    proc.wait()
    
    if not eph_key:
        return False, "Failed to capture ephemeral key"
        
    # 9. Recovery (Ephemeral Key)
    print("  [9/9] Sunseal Recovery (Ephemeral Key)...")
    rc, out = run_cmd([str(VENV_PYTHON), str(UNSEAL_PATH), "-i", str(OUT_EPHEMERAL), "-o", str(REC_EPH), "-c", "ssn", "--key", eph_key])
    with open(REC_EPH, "r") as f:
        data = f.read()
        if "123-45-678" not in data:
            return False, f"Ephemeral recovery failed. Content: {data[:100]}"
            
    return True, "All phases passed."

def main():
    successes = 0
    failures = []
    
    for i in range(1, ITERATIONS + 1):
        ok, msg = run_iteration(i)
        if ok:
            print(f"\n✅ ITERATION {i} SUCCESSFUL")
            successes += 1
        else:
            print(f"\n❌ ITERATION {i} FAILED: {msg}")
            failures.append((i, msg))
            break # Stop on first failure to debug
            
    clean_environment()
    
    print("\n" + "="*50)
    print("  HOLISTIC SIMULATION REPORT")
    print("="*50)
    print(f"  Target Iterations: {ITERATIONS}")
    print(f"  Successful Runs:   {successes}")
    
    if successes == ITERATIONS:
        print("\n🏆 SYSTEM IS STABLE & FLAKE-FREE. ALL COMPONENTS VERIFIED.")
        exit(0)
    else:
        print("\n⚠️ SYSTEM UNSTABLE. REGRESSIONS DETECTED.")
        for f in failures:
            print(f"  - Iteration {f[0]}: {f[1]}")
        exit(1)

if __name__ == "__main__":
    main()
